#include<stm32f4xx.h>
#include<led.h>
#include<delay.h>
int main()
{
	delay_init(168);
	LED_Init();
	while(1)
	{
		GPIOF->ODR&=~(1<<2);
		GPIOF->ODR|=1<<1;
		GPIOF->ODR&=~(1<<3);
		GPIOF->ODR&=~(1<<4);
		GPIOF->ODR&=~(1<<5);
		GPIOF->ODR&=~(1<<6);
		GPIOF->ODR&=~(1<<7);
		GPIOF->ODR&=~(1<<9);
		GPIOF->ODR&=~(1<<10);
		GPIOG->ODR&=~(1<<5);
		delay_ms(200);
    GPIOF->ODR&=~(1<<1);
		GPIOF->ODR|=1<<2;
		GPIOF->ODR&=~(1<<3);
		GPIOF->ODR&=~(1<<4);
		GPIOF->ODR&=~(1<<5);
		GPIOF->ODR&=~(1<<6);
		GPIOF->ODR&=~(1<<7);
		GPIOF->ODR&=~(1<<9);
		GPIOF->ODR&=~(1<<10);
		GPIOG->ODR&=~(1<<5);
		delay_ms(200);
		GPIOF->ODR&=~(1<<1);
		GPIOF->ODR|=1<<3;
		GPIOF->ODR&=~(1<<2);
		GPIOF->ODR&=~(1<<4);
		GPIOF->ODR&=~(1<<5);
		GPIOF->ODR&=~(1<<6);
		GPIOF->ODR&=~(1<<7);
		GPIOF->ODR&=~(1<<9);
		GPIOF->ODR&=~(1<<10);
		GPIOG->ODR&=~(1<<5);
		delay_ms(200);
		GPIOF->ODR&=~(1<<1);
		GPIOF->ODR|=1<<4;
		GPIOF->ODR&=~(1<<3);
		GPIOF->ODR&=~(1<<2);
		GPIOF->ODR&=~(1<<5);
		GPIOF->ODR&=~(1<<6);
		GPIOF->ODR&=~(1<<7);
		GPIOF->ODR&=~(1<<9);
		GPIOF->ODR&=~(1<<10);
		GPIOG->ODR&=~(1<<5);
		delay_ms(200);
		GPIOF->ODR&=~(1<<1);
		GPIOF->ODR|=1<<5;
		GPIOF->ODR&=~(1<<3);
		GPIOF->ODR&=~(1<<4);
		GPIOF->ODR&=~(1<<2);
		GPIOF->ODR&=~(1<<6);
		GPIOF->ODR&=~(1<<7);
		GPIOF->ODR&=~(1<<9);
		GPIOF->ODR&=~(1<<10);
		GPIOG->ODR&=~(1<<5);
		delay_ms(200);
		GPIOF->ODR&=~(1<<1);
		GPIOF->ODR|=1<<6;
		GPIOF->ODR&=~(1<<3);
		GPIOF->ODR&=~(1<<4);
		GPIOF->ODR&=~(1<<5);
		GPIOF->ODR&=~(1<<2);
		GPIOF->ODR&=~(1<<7);
		GPIOF->ODR&=~(1<<9);
		GPIOF->ODR&=~(1<<10);
		GPIOG->ODR&=~(1<<5);
		delay_ms(200);
		GPIOF->ODR&=~(1<<1);
		GPIOF->ODR|=1<<7;
		GPIOF->ODR&=~(1<<3);
		GPIOF->ODR&=~(1<<4);
		GPIOF->ODR&=~(1<<5);
		GPIOF->ODR&=~(1<<6);
		GPIOF->ODR&=~(1<<2);
		GPIOF->ODR&=~(1<<9);
		GPIOF->ODR&=~(1<<10);
		GPIOG->ODR&=~(1<<5);
		delay_ms(200);
		GPIOF->ODR&=~(1<<1);
		GPIOG->ODR|=1<<5;
		GPIOF->ODR&=~(1<<3);
		GPIOF->ODR&=~(1<<4);
		GPIOF->ODR&=~(1<<5);
		GPIOF->ODR&=~(1<<6);
		GPIOF->ODR&=~(1<<7);
		GPIOF->ODR&=~(1<<9);
		GPIOF->ODR&=~(1<<10);
		GPIOF->ODR&=~(1<<2);
		delay_ms(200);
		GPIOF->ODR&=~(1<<1);
		GPIOF->ODR|=1<<9;
		GPIOF->ODR&=~(1<<3);
		GPIOF->ODR&=~(1<<4);
		GPIOF->ODR&=~(1<<5);
		GPIOF->ODR&=~(1<<6);
		GPIOF->ODR&=~(1<<7);
		GPIOF->ODR&=~(1<<2);
		GPIOF->ODR&=~(1<<10);
		GPIOG->ODR&=~(1<<5);
		delay_ms(200);
		GPIOF->ODR&=~(1<<1);
		GPIOF->ODR|=1<<10;
		GPIOF->ODR&=~(1<<3);
		GPIOF->ODR&=~(1<<4);
		GPIOF->ODR&=~(1<<5);
		GPIOF->ODR&=~(1<<6);
		GPIOF->ODR&=~(1<<7);
		GPIOF->ODR&=~(1<<9);
		GPIOF->ODR&=~(1<<2);
		GPIOG->ODR&=~(1<<5);
		delay_ms(200);
	
	}
	return 0;
	
}

